/**
 * Authorization Model Adapter
 *
 * Compiles Authorization IR → OpenFGA authorization model DSL.
 * This adapter is vendor-AWARE (it targets OpenFGA) but domain-NEUTRAL
 * (it contains zero domain-specific logic).
 */

import { CompilationAdapter } from './base.js';

function toSnakeCase(str) {
  return str
    .replace(/([a-z])([A-Z])/g, '$1_$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1_$2')
    .toLowerCase();
}

export class AuthorizationModelAdapter extends CompilationAdapter {
  name() {
    return 'authorization-model-openfga';
  }

  consumes() {
    return ['ontology', 'authorization'];
  }

  compile(ir, config = {}) {
    const warnings = [];
    const lines = [];

    lines.push(`# Generated by Domain Definition IR Compiler`);
    lines.push(`# Domain: ${ir.name || 'unknown'}`);
    lines.push(`# WARNING: This is compiled output. Do not edit manually.`);
    lines.push('');
    lines.push('model');
    lines.push('  schema 1.1');
    lines.push('');

    // Platform hierarchy types (always present)
    lines.push('# --- Platform hierarchy (from platform tenancy model) ---');
    lines.push('');
    lines.push('type platform');
    lines.push('  relations');
    lines.push('    define admin: [user]');
    lines.push('');
    lines.push('type product');
    lines.push('  relations');
    lines.push('    define platform: [platform]');
    lines.push('    define admin: [user] or admin from platform');
    lines.push('');
    lines.push('type tenant');
    lines.push('  relations');
    lines.push('    define product: [product]');
    lines.push('    define admin: [user] or admin from product');
    lines.push('    define member: [user, service_account]');
    lines.push('');
    lines.push('type workspace');
    lines.push('  relations');
    lines.push('    define tenant: [tenant]');
    lines.push('    define lead: [user]');
    lines.push('    define contributor: [user]');
    lines.push('    define viewer: [user] or contributor');
    lines.push('');
    lines.push('type user');
    lines.push('');
    lines.push('type service_account');
    lines.push('');
    lines.push('type agent');
    lines.push('  relations');
    lines.push('    define delegated_by: [user, service_account]');
    lines.push('    define owner: [user]');
    lines.push('');

    lines.push('# --- Domain-specific types (compiled from authorization IR) ---');
    lines.push('');

    // Generate type definitions from ontology entities
    if (ir.ontology?.entities) {
      for (const [entityName, entity] of Object.entries(ir.ontology.entities)) {
        const typeName = toSnakeCase(entityName);
        lines.push(`type ${typeName}`);
        lines.push('  relations');
        lines.push('    define tenant: [tenant]');

        // Collect role names from authorization IR
        const entityRoles = this._rolesForEntity(entityName, ir.authorization);

        // Default CRUD relations
        lines.push('    define viewer: [user, agent] or member from tenant');
        lines.push('    define editor: [user, agent] or admin from tenant');
        lines.push('    define creator: [user, agent] or admin from tenant');
        lines.push('    define deleter: [user, agent] or admin from tenant');

        // Custom relationships from authorization IR
        if (ir.authorization?.relationships) {
          for (const [relName, rel] of Object.entries(ir.authorization.relationships)) {
            if (rel.object === entityName || rel.on_entity === entityName) {
              const relation = toSnakeCase(rel.relation || relName);
              lines.push(`    define ${relation}: [user, agent]`);
            }
          }
        }

        lines.push('');
      }
    }

    // Generate role-to-permission mappings as comments
    // (OpenFGA doesn't have "roles" natively — they're modeled as relationships)
    if (ir.authorization?.roles) {
      lines.push('# --- Role definitions (for reference — implemented via stored tuples) ---');
      for (const [roleName, role] of Object.entries(ir.authorization.roles)) {
        lines.push(`# Role: ${roleName}`);
        if (role.can_view) {
          lines.push(`#   can_view: ${JSON.stringify(role.can_view)}`);
        }
        if (role.can_create) {
          lines.push(`#   can_create: ${JSON.stringify(role.can_create)}`);
        }
        if (role.can_update) {
          lines.push(`#   can_update: ${JSON.stringify(role.can_update)}`);
        }
        if (role.can_delete) {
          lines.push(`#   can_delete: ${JSON.stringify(role.can_delete)}`);
        }
        if (role.description) {
          lines.push(`#   description: ${role.description}`);
        }
      }
      lines.push('');
    }

    return {
      adapterName: this.name(),
      targetFormat: 'openfga-dsl',
      content: lines.join('\n'),
      warnings,
    };
  }

  _rolesForEntity(entityName, authorization) {
    const roles = [];
    if (!authorization?.roles) return roles;

    for (const [roleName, role] of Object.entries(authorization.roles)) {
      const allTargets = [
        ...(role.can_view || []),
        ...(role.can_create || []),
        ...(role.can_update || []),
        ...(role.can_delete || []),
      ];

      const references = allTargets.some(t =>
        t.toLowerCase().includes(entityName.toLowerCase()) ||
        t.includes('all_') ||
        t.includes('any_')
      );

      if (references) {
        roles.push(roleName);
      }
    }

    return roles;
  }

  validate(output) {
    const errors = [];

    if (!output.content) {
      errors.push('Compilation produced empty output');
    }

    if (output.content && !output.content.includes('model')) {
      errors.push('Output missing "model" declaration');
    }

    if (output.content && !output.content.includes('schema 1.1')) {
      errors.push('Output missing schema version');
    }

    // Verify platform hierarchy types are present
    for (const type of ['platform', 'product', 'tenant', 'workspace', 'user', 'agent']) {
      if (!output.content.includes(`type ${type}`)) {
        errors.push(`Output missing platform hierarchy type: ${type}`);
      }
    }

    return { valid: errors.length === 0, errors };
  }
}
