-- Generated by Domain Definition IR Compiler
-- Domain: iot-monitoring
-- Version: 1.0.0
-- Generated at: 2026-08-13T22:10:22.841Z
-- WARNING: This is compiled output. Do not edit manually.
--
-- This adapter is domain-neutral. It compiled the ontology sub-IR
-- without any knowledge of the specific domain.
CREATE TABLE IF NOT EXISTS public.facility (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  facility_id UUID NOT NULL,
  name TEXT NOT NULL,
  location JSONB NOT NULL,
  facility_type TEXT NOT NULL CHECK (facility_type IN ('manufacturing_plant', 'warehouse', 'refinery', 'power_station', 'water_treatment', 'data_center', 'distribution_hub')),
  operational_status TEXT NOT NULL CHECK (operational_status IN ('active', 'idle', 'shutdown', 'under_construction')),
  commissioned_at TIMESTAMPTZ NOT NULL,
  max_device_capacity INTEGER,
  metadata JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_facility_tenant ON public.facility(tenant_id);
ALTER TABLE public.facility ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_facility ON public.facility USING (tenant_id = current_setting('app.current_tenant_id')::UUID);

CREATE TABLE IF NOT EXISTS public.device (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  device_id UUID NOT NULL,
  facility_id UUID NOT NULL,
  name TEXT NOT NULL,
  device_type TEXT NOT NULL CHECK (device_type IN ('pump', 'motor', 'compressor', 'turbine', 'hvac_unit', 'conveyor', 'generator', 'transformer', 'valve', 'heat_exchanger')),
  manufacturer TEXT,
  model_number TEXT,
  serial_number TEXT NOT NULL,
  operational_state TEXT NOT NULL CHECK (operational_state IN ('online', 'offline', 'maintenance', 'degraded', 'decommissioned')),
  criticality TEXT NOT NULL CHECK (criticality IN ('critical', 'high', 'medium', 'low')),
  installed_at TIMESTAMPTZ NOT NULL,
  last_maintenance_at TIMESTAMPTZ,
  firmware_version TEXT,
  expected_lifespan_hours INTEGER,
  accumulated_run_hours DOUBLE PRECISION,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_device_tenant ON public.device(tenant_id);
ALTER TABLE public.device ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_device ON public.device USING (tenant_id = current_setting('app.current_tenant_id')::UUID);

CREATE TABLE IF NOT EXISTS public.sensor (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  sensor_id UUID NOT NULL,
  device_id UUID NOT NULL,
  name TEXT NOT NULL,
  sensor_type TEXT NOT NULL CHECK (sensor_type IN ('temperature', 'pressure', 'vibration', 'humidity', 'flow_rate', 'voltage', 'current', 'power', 'rpm', 'acoustic', 'gas_concentration', 'level', 'ph', 'conductivity')),
  unit_of_measure TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('active', 'inactive', 'calibrating', 'faulty', 'decommissioned')),
  sampling_interval_seconds INTEGER NOT NULL,
  calibration JSONB NOT NULL,
  thresholds JSONB NOT NULL,
  installed_at TIMESTAMPTZ NOT NULL,
  location_on_device TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_sensor_tenant ON public.sensor(tenant_id);
ALTER TABLE public.sensor ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_sensor ON public.sensor USING (tenant_id = current_setting('app.current_tenant_id')::UUID);

CREATE TABLE IF NOT EXISTS public.sensor_reading (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  reading_id UUID NOT NULL,
  sensor_id UUID NOT NULL,
  timestamp TIMESTAMPTZ NOT NULL,
  value DOUBLE PRECISION NOT NULL,
  raw_value DOUBLE PRECISION,
  quality TEXT NOT NULL CHECK (quality IN ('good', 'uncertain', 'bad', 'stale')),
  ingested_at TIMESTAMPTZ NOT NULL,
  anomaly_score DOUBLE PRECISION,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_sensor_reading_tenant ON public.sensor_reading(tenant_id);
ALTER TABLE public.sensor_reading ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_sensor_reading ON public.sensor_reading USING (tenant_id = current_setting('app.current_tenant_id')::UUID);

CREATE TABLE IF NOT EXISTS public.alert (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  alert_id UUID NOT NULL,
  device_id UUID NOT NULL,
  sensor_id UUID,
  facility_id UUID NOT NULL,
  alert_type TEXT NOT NULL CHECK (alert_type IN ('threshold_breach', 'anomaly_detected', 'device_offline', 'device_degraded', 'calibration_overdue', 'communication_loss', 'rate_of_change', 'pattern_deviation')),
  severity TEXT NOT NULL CHECK (severity IN ('critical', 'warning', 'info')),
  status TEXT NOT NULL CHECK (status IN ('raised', 'acknowledged', 'investigating', 'resolved', 'dismissed', 'auto_resolved')),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  trigger_value DOUBLE PRECISION,
  trigger_threshold DOUBLE PRECISION,
  raised_at TIMESTAMPTZ NOT NULL,
  acknowledged_at TIMESTAMPTZ,
  acknowledged_by TEXT,
  resolved_at TIMESTAMPTZ,
  resolved_by TEXT,
  resolution_notes TEXT,
  deduplication_key TEXT NOT NULL,
  correlation_group TEXT,
  escalation_level INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_alert_tenant ON public.alert(tenant_id);
ALTER TABLE public.alert ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_alert ON public.alert USING (tenant_id = current_setting('app.current_tenant_id')::UUID);

CREATE TABLE IF NOT EXISTS public.maintenance_order (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  order_id UUID NOT NULL,
  device_id UUID NOT NULL,
  facility_id UUID NOT NULL,
  alert_id UUID,
  order_type TEXT NOT NULL CHECK (order_type IN ('reactive', 'preventive', 'predictive', 'corrective', 'inspection')),
  priority TEXT NOT NULL CHECK (priority IN ('emergency', 'urgent', 'normal', 'low')),
  status TEXT NOT NULL CHECK (status IN ('requested', 'estimated', 'pending_approval', 'approved', 'scheduled', 'in_progress', 'completed', 'verified', 'cancelled')),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  requested_by TEXT NOT NULL,
  assigned_to TEXT,
  estimated_cost DOUBLE PRECISION,
  actual_cost DOUBLE PRECISION,
  estimated_duration_hours DOUBLE PRECISION,
  actual_duration_hours DOUBLE PRECISION,
  requires_device_shutdown BOOLEAN NOT NULL DEFAULT FALSE,
  parts_required JSONB,
  created_at TIMESTAMPTZ NOT NULL,
  approved_at TIMESTAMPTZ,
  approved_by TEXT,
  scheduled_start TIMESTAMPTZ,
  scheduled_end TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  verification_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_maintenance_order_tenant ON public.maintenance_order(tenant_id);
ALTER TABLE public.maintenance_order ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_maintenance_order ON public.maintenance_order USING (tenant_id = current_setting('app.current_tenant_id')::UUID);

CREATE TABLE IF NOT EXISTS public.personnel_assignment (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  assignment_id UUID NOT NULL,
  user_id TEXT NOT NULL,
  facility_id UUID NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('operator', 'engineer', 'facility_manager', 'maintenance_tech', 'admin')),
  assigned_at TIMESTAMPTZ NOT NULL,
  valid_until TIMESTAMPTZ,
  device_scope JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_personnel_assignment_tenant ON public.personnel_assignment(tenant_id);
ALTER TABLE public.personnel_assignment ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_personnel_assignment ON public.personnel_assignment USING (tenant_id = current_setting('app.current_tenant_id')::UUID);
