-- Generated by Domain Definition IR Compiler
-- Domain: healthcare-clinic
-- Version: 1.0.0
-- Generated at: 2026-08-13T22:10:22.827Z
-- WARNING: This is compiled output. Do not edit manually.
--
-- This adapter is domain-neutral. It compiled the ontology sub-IR
-- without any knowledge of the specific domain.
CREATE TABLE IF NOT EXISTS public.patient (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  patient_id UUID,
  medical_record_number TEXT UNIQUE,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  date_of_birth DATE NOT NULL,
  gender TEXT CHECK (gender IN ('male', 'female', 'non_binary', 'prefer_not_to_say', 'other')),
  email TEXT,
  phone TEXT,
  address JSONB,
  emergency_contact_name TEXT,
  emergency_contact_phone TEXT,
  primary_language TEXT DEFAULT 'en',
  requires_interpreter BOOLEAN DEFAULT FALSE,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'deceased', 'transferred')),
  registration_date TIMESTAMPTZ,
  last_visit_date TIMESTAMPTZ,
  notes TEXT,
  assigned_clinic_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_patient_assigned_clinic FOREIGN KEY (assigned_clinic_id) REFERENCES public.clinic(id)
);
CREATE INDEX IF NOT EXISTS idx_patient_tenant ON public.patient(tenant_id);
ALTER TABLE public.patient ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_patient ON public.patient USING (tenant_id = current_setting('app.current_tenant_id')::UUID);

CREATE TABLE IF NOT EXISTS public.practitioner (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  practitioner_id UUID,
  npi_number TEXT NOT NULL UNIQUE,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  credential_suffix TEXT,
  specialty TEXT NOT NULL CHECK (specialty IN ('family_medicine', 'internal_medicine', 'pediatrics', 'obstetrics_gynecology', 'cardiology', 'dermatology', 'orthopedics', 'psychiatry', 'neurology', 'general_surgery', 'ophthalmology', 'urgent_care')),
  email TEXT NOT NULL,
  phone TEXT,
  license_number TEXT NOT NULL,
  license_state TEXT NOT NULL,
  license_expiration DATE NOT NULL,
  accepting_new_patients BOOLEAN DEFAULT TRUE,
  max_daily_appointments INTEGER DEFAULT 20,
  default_appointment_duration_minutes INTEGER DEFAULT 30,
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'on_leave', 'inactive', 'suspended')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_practitioner_tenant ON public.practitioner(tenant_id);
ALTER TABLE public.practitioner ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_practitioner ON public.practitioner USING (tenant_id = current_setting('app.current_tenant_id')::UUID);

CREATE TABLE IF NOT EXISTS public.appointment (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  appointment_id UUID,
  appointment_type TEXT NOT NULL CHECK (appointment_type IN ('new_patient', 'follow_up', 'annual_physical', 'urgent', 'telehealth', 'procedure', 'consultation', 'lab_review')),
  scheduled_start TIMESTAMPTZ NOT NULL,
  scheduled_end TIMESTAMPTZ NOT NULL,
  actual_start TIMESTAMPTZ,
  actual_end TIMESTAMPTZ,
  status TEXT DEFAULT 'requested' CHECK (status IN ('requested', 'pending_insurance', 'confirmed', 'checked_in', 'in_progress', 'completed', 'cancelled', 'no_show', 'rescheduled')),
  cancellation_reason TEXT CHECK (cancellation_reason IN ('patient_request', 'practitioner_unavailable', 'insurance_not_verified', 'weather', 'facility_issue', 'other')),
  cancellation_note TEXT,
  chief_complaint TEXT,
  visit_notes TEXT,
  is_emergency BOOLEAN DEFAULT FALSE,
  requires_interpreter BOOLEAN DEFAULT FALSE,
  interpreter_language TEXT,
  copay_amount NUMERIC,
  copay_collected BOOLEAN DEFAULT FALSE,
  check_in_time TIMESTAMPTZ,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ,
  created_by UUID NOT NULL,
  patient_id UUID,
  practitioner_id UUID,
  clinic_id UUID,
  insurance_authorization_id UUID,
  originating_referral_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_appointment_patient FOREIGN KEY (patient_id) REFERENCES public.patient(id),
  CONSTRAINT fk_appointment_practitioner FOREIGN KEY (practitioner_id) REFERENCES public.practitioner(id),
  CONSTRAINT fk_appointment_clinic FOREIGN KEY (clinic_id) REFERENCES public.clinic(id),
  CONSTRAINT fk_appointment_insurance_authorization FOREIGN KEY (insurance_authorization_id) REFERENCES public.insurance_coverage(id),
  CONSTRAINT fk_appointment_originating_referral FOREIGN KEY (originating_referral_id) REFERENCES public.referral(id)
);
CREATE INDEX IF NOT EXISTS idx_appointment_tenant ON public.appointment(tenant_id);
ALTER TABLE public.appointment ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_appointment ON public.appointment USING (tenant_id = current_setting('app.current_tenant_id')::UUID);

CREATE TABLE IF NOT EXISTS public.clinic (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  clinic_id UUID,
  name TEXT NOT NULL,
  clinic_type TEXT NOT NULL CHECK (clinic_type IN ('primary_care', 'specialty', 'urgent_care', 'telehealth', 'surgical_center')),
  address JSONB NOT NULL,
  phone TEXT NOT NULL,
  fax TEXT,
  email TEXT,
  timezone TEXT NOT NULL,
  operating_hours JSONB NOT NULL,
  max_concurrent_appointments INTEGER DEFAULT 10,
  status TEXT DEFAULT 'open' CHECK (status IN ('open', 'closed_temporarily', 'closed_permanently')),
  accepts_walk_ins BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_clinic_tenant ON public.clinic(tenant_id);
ALTER TABLE public.clinic ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_clinic ON public.clinic USING (tenant_id = current_setting('app.current_tenant_id')::UUID);

CREATE TABLE IF NOT EXISTS public.insurance_coverage (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  coverage_id UUID,
  insurance_provider TEXT NOT NULL,
  plan_name TEXT NOT NULL,
  plan_type TEXT NOT NULL CHECK (plan_type IN ('hmo', 'ppo', 'epo', 'pos', 'hdhp', 'medicaid', 'medicare', 'tricare', 'self_pay')),
  member_id TEXT NOT NULL,
  group_number TEXT,
  subscriber_name TEXT NOT NULL,
  subscriber_relationship TEXT NOT NULL CHECK (subscriber_relationship IN ('self', 'spouse', 'child', 'other')),
  effective_date DATE NOT NULL,
  termination_date DATE,
  copay_amount NUMERIC,
  deductible_amount NUMERIC,
  deductible_met NUMERIC DEFAULT 0,
  verification_status TEXT DEFAULT 'unverified' CHECK (verification_status IN ('unverified', 'pending', 'verified_active', 'verified_inactive', 'verification_failed')),
  last_verified_at TIMESTAMPTZ,
  verification_notes TEXT,
  requires_preauthorization BOOLEAN DEFAULT FALSE,
  preauthorization_phone TEXT,
  priority TEXT NOT NULL CHECK (priority IN ('primary', 'secondary', 'tertiary')),
  patient_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_insurance_coverage_patient FOREIGN KEY (patient_id) REFERENCES public.patient(id)
);
CREATE INDEX IF NOT EXISTS idx_insurance_coverage_tenant ON public.insurance_coverage(tenant_id);
ALTER TABLE public.insurance_coverage ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_insurance_coverage ON public.insurance_coverage USING (tenant_id = current_setting('app.current_tenant_id')::UUID);

CREATE TABLE IF NOT EXISTS public.referral (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  referral_id UUID,
  referral_number TEXT UNIQUE,
  referral_type TEXT NOT NULL CHECK (referral_type IN ('internal', 'external_inbound', 'external_outbound')),
  urgency TEXT DEFAULT 'routine' CHECK (urgency IN ('routine', 'urgent', 'emergent')),
  target_specialty TEXT NOT NULL CHECK (target_specialty IN ('family_medicine', 'internal_medicine', 'pediatrics', 'obstetrics_gynecology', 'cardiology', 'dermatology', 'orthopedics', 'psychiatry', 'neurology', 'general_surgery', 'ophthalmology', 'urgent_care')),
  reason TEXT NOT NULL,
  clinical_notes TEXT,
  diagnosis_codes JSONB,
  status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'submitted', 'under_review', 'approved', 'denied', 'expired', 'completed', 'cancelled')),
  denial_reason TEXT,
  authorized_visits INTEGER DEFAULT 1,
  visits_used INTEGER DEFAULT 0,
  valid_from DATE NOT NULL,
  valid_until DATE NOT NULL,
  requires_insurance_auth BOOLEAN DEFAULT FALSE,
  insurance_auth_number TEXT,
  created_at TIMESTAMPTZ,
  reviewed_at TIMESTAMPTZ,
  reviewed_by UUID,
  referred_patient_id UUID,
  referring_practitioner_id UUID,
  target_practitioner_id UUID,
  originating_appointment_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_referral_referred_patient FOREIGN KEY (referred_patient_id) REFERENCES public.patient(id),
  CONSTRAINT fk_referral_referring_practitioner FOREIGN KEY (referring_practitioner_id) REFERENCES public.practitioner(id),
  CONSTRAINT fk_referral_target_practitioner FOREIGN KEY (target_practitioner_id) REFERENCES public.practitioner(id),
  CONSTRAINT fk_referral_originating_appointment FOREIGN KEY (originating_appointment_id) REFERENCES public.appointment(id)
);
CREATE INDEX IF NOT EXISTS idx_referral_tenant ON public.referral(tenant_id);
ALTER TABLE public.referral ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_referral ON public.referral USING (tenant_id = current_setting('app.current_tenant_id')::UUID);

CREATE TABLE IF NOT EXISTS public.schedule_block (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  block_id UUID,
  block_type TEXT NOT NULL CHECK (block_type IN ('available', 'unavailable', 'lunch', 'administrative', 'on_call')),
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ NOT NULL,
  recurrence_rule TEXT,
  recurrence_end DATE,
  reason TEXT,
  appointment_types_allowed JSONB,
  practitioner_id UUID,
  clinic_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_schedule_block_practitioner FOREIGN KEY (practitioner_id) REFERENCES public.practitioner(id),
  CONSTRAINT fk_schedule_block_clinic FOREIGN KEY (clinic_id) REFERENCES public.clinic(id)
);
CREATE INDEX IF NOT EXISTS idx_schedule_block_tenant ON public.schedule_block(tenant_id);
ALTER TABLE public.schedule_block ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_schedule_block ON public.schedule_block USING (tenant_id = current_setting('app.current_tenant_id')::UUID);

CREATE TABLE IF NOT EXISTS public.practitioner_clinic_assignment (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id UUID NOT NULL,
  assignment_id UUID,
  is_primary_location BOOLEAN DEFAULT FALSE,
  start_date DATE NOT NULL,
  end_date DATE,
  assigned_room TEXT,
  practitioner_id UUID,
  clinic_id UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT fk_practitioner_clinic_assignment_practitioner FOREIGN KEY (practitioner_id) REFERENCES public.practitioner(id),
  CONSTRAINT fk_practitioner_clinic_assignment_clinic FOREIGN KEY (clinic_id) REFERENCES public.clinic(id)
);
CREATE INDEX IF NOT EXISTS idx_practitioner_clinic_assignment_tenant ON public.practitioner_clinic_assignment(tenant_id);
ALTER TABLE public.practitioner_clinic_assignment ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_practitioner_clinic_assignment ON public.practitioner_clinic_assignment USING (tenant_id = current_setting('app.current_tenant_id')::UUID);

CREATE TABLE IF NOT EXISTS public.practitioner_clinic (
  practitioner_id UUID NOT NULL REFERENCES public.practitioner(id),
  clinic_id UUID NOT NULL REFERENCES public.clinic(id),
  tenant_id UUID NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (practitioner_id, clinic_id)
);
ALTER TABLE public.practitioner_clinic ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_practitioner_clinic ON public.practitioner_clinic USING (tenant_id = current_setting('app.current_tenant_id')::UUID);

CREATE TABLE IF NOT EXISTS public.clinic_practitioner (
  clinic_id UUID NOT NULL REFERENCES public.clinic(id),
  practitioner_id UUID NOT NULL REFERENCES public.practitioner(id),
  tenant_id UUID NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (clinic_id, practitioner_id)
);
ALTER TABLE public.clinic_practitioner ENABLE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation_clinic_practitioner ON public.clinic_practitioner USING (tenant_id = current_setting('app.current_tenant_id')::UUID);
